hello hooks

diff --git a/.githooks/post-commit b/.githooks/post-commit
--- a/.githooks/post-commit
+++ b/.githooks/post-commit
@@ -2,15 +2,41 @@
 
 set -euo pipefail
 
-PASSWORD_FILE="password"
+# ====================================
 
-# ask user if he wants to shred it
-# trap 'shred -u -n 5 "${PASSWORD_FILE}"' EXIT SIGINT SIGTERM
+main() {
+  echo "======= post-commit started ======="
 
-FILES_TO_DECRYPT=($(find secrets/ -type f))
+  FILES_TO_DECRYPT=($(git show --name-only --oneline HEAD -- secrets/ | sed '1d'))
 
-echo "=== DECRYPTION =========================="
+  if [ "${#FILES_TO_DECRYPT[@]}" -eq 0 ]; then
 
-ansible-vault decrypt --vault-password-file "${PASSWORD_FILE}" -- "${FILES_TO_DECRYPT[@]}"
+    echo "No secrets added to commit."
+    echo "Skipping post-commit hook decryption"
 
-echo -e "\n"
+  else
+
+    PASSWORD_FILE="$HOME/pers/password"
+    if [ ! -s "${PASSWORD_FILE}" ]; then
+      echo "${PASSWORD_FILE} missing. Created now."
+      echo "Enter correct password in the file and try again"
+      touch "${PASSWORD_FILE}" && chmod 600 "${PASSWORD_FILE}"
+      exit 1
+    fi
+
+    echo "Files to be decrypted:"
+    for file in "${FILES_TO_DECRYPT[@]}"; do
+        echo "  - $file"
+    done
+
+    echo "Decryption..."
+    ansible-vault decrypt --vault-password-file "${PASSWORD_FILE}" -- "${FILES_TO_DECRYPT[@]}"
+
+    trap 'shred -u -n 5 "${PASSWORD_FILE}"' EXIT SIGINT SIGTERM
+
+  fi
+
+  echo -e "======= post-commit finished =======\n"
+}
+
+main
diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -2,14 +2,46 @@
 
 set -euo pipefail
 
-PASSWORD_FILE="password"
+# ====================================
+#
+# TODO: if there are no files to encrypt or decrypt, we don't need password file and skip hooks altogether
 
-FILES_TO_ENCRYPT=($(find secrets/ -type f))
+main() {
+  echo "======= pre-commit started ======="
 
-echo "=== ENCRYPTION =========================="
+  FILES_TO_ENCRYPT=($(git diff --name-only --cached -- secrets/))
 
-ansible-vault encrypt --vault-password-file "${PASSWORD_FILE}" -- "${FILES_TO_ENCRYPT[@]}"
+  if [ "${#FILES_TO_ENCRYPT[@]}" -eq 0 ]; then
+    echo "No secrets added to commit."
 
-git add "${FILES_TO_ENCRYPT[@]}"
+    echo "Skipping pre-commit hook encryption"
 
-echo -e "\n"
+  else
+
+    PASSWORD_FILE="$HOME/pers/password"
+    if [ ! -s "${PASSWORD_FILE}" ]; then
+      echo "${PASSWORD_FILE} missing. Created now."
+      echo "Enter correct password in the file and try again"
+      touch "${PASSWORD_FILE}" && chmod 600 "${PASSWORD_FILE}"
+      exit 1
+    fi
+
+    echo "Files to be encrypted:"
+    for file in "${FILES_TO_ENCRYPT[@]}"; do
+      echo "  - $file"
+    done
+
+    echo "Encryption..."
+    ansible-vault encrypt --vault-password-file "${PASSWORD_FILE}" -- "${FILES_TO_ENCRYPT[@]}"
+
+    echo "Re-adding to index..."
+    for file in "${FILES_TO_ENCRYPT[@]}"; do
+      git add "$file"
+    done
+  fi
+
+  echo -e "======= pre-commit finished =======\n"
+
+}
+
+main
