feat

diff --git a/scripts/new_sessionizer b/scripts/new_sessionizer
--- a/scripts/new_sessionizer
+++ b/scripts/new_sessionizer
@@ -8,45 +8,53 @@ main() {
       --prompt="Workdir?: " --delimiter='/' --with-nth='4..')
   [ -z "$session" ] && return 0
 
+  local tmux_session_name=$(basename "$session" | tr '.' '_')
+
   # Check if the tmux server is running
   if ! tmux ls &>/dev/null; then
     tmux start-server
   fi
 
   # Check if the session exists
-  if ! tmux has-session -t "$session" 2>/dev/null; then
-    # tmux new-session -s "$session" -c "$session" -d
+  # if ! tmux has-session -t "$session" 2>/dev/null; then
+  # tmux new-session -s "$session" -c "$session" -d
 
-    is_bare=$(git rev-parse --is-bare-repository 2>/dev/null)
+  # is_bare=$(git rev-parse --is-bare-repository 2>/dev/null)
+  #
+  # if [ "$is_bare" = "true" ]; then
+  #   source "$HOME/pers/scripts/create_worktree"
+  #
+  #   worktree=$(git worktree list --porcelain 2>/dev/null | awk '/worktree /{print $2}' | tail -n1)
+  #   if [ -n "$worktree" ]; then
+  #     cd "$worktree" || return 1
+  #   else
+  #     echo "Failed to locate a valid worktree."
+  #     return 1
+  #   fi
+  # fi
 
-    if [ "$is_bare" = "true" ]; then
-      source "$HOME/pers/scripts/create_worktree"
+  # tmux new-session -s "$session" -c "$session" -d
+  # tmux send-keys -t "$session" "nvim +terminal +tabnew +Oil +Telescope" C-m
+  #   tmux send-keys -t "$session" "SESSIONIZER_START=1 nvim +terminal +tabnew +Oil" C-m
+  # fi
 
-      worktree=$(git worktree list --porcelain 2>/dev/null | awk '/worktree /{print $2}' | tail -n1)
-      if [ -n "$worktree" ]; then
-        cd "$worktree" || return 1
-      else
-        echo "Failed to locate a valid worktree."
-        return 1
-      fi
-    fi
+  # Check if the session exists
+  if ! tmux has-session -t "$tmux_session_name" 2>/dev/null; then
+    # Create the new session, setting the working directory
+    tmux new-session -s "$tmux_session_name" -c "$session" -d
 
-    tmux new-session -s "$session" -c "$session" -d
-    tmux send-keys -t "$session" "nvim" C-m
+    # Send the command to Neovim.
+    # We set an environment variable SESSIONIZER_START=1 that our nvim config can detect.
+    # This is more reliable than sending multiple commands.
+    tmux send-keys -t "$tmux_session_name" "SESSIONIZER_START=true nvim" C-m
   fi
 
-  Attach to the tmux session or switch to it
+  # Attach to the tmux session or switch to it
   if [ -z "$TMUX" ]; then
-    tmux attach-session -t "$session"
+    tmux attach-session -t "$tmux_session_name"
   else
-    tmux switch-client -t "$session"
+    tmux switch-client -t "$tmux_session_name"
   fi
-
-  # nvim \
-  #   +terminal \
-  #   +tabnew \
-  #   +"lua require('oil').open(vim.loop.cwd())" \
-  #   +"Telescope find_files"
 }
 
 main "$@"
